apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeconfigtoken

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubeconfigtoken
rules:
- apiGroups: [""]
  resources: ["pods", "deployments", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["pods", "deployments"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubeconfigtoken
subjects:
- kind: ServiceAccount
  name: kubeconfigtoken
  namespace: default
roleRef:
  kind: ClusterRole
  name: kubeconfigtoken
  apiGroup: rbac.authorization.k8s.io